name: Build Docker Image & Push into ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Install npx
      run: |
        npm i -g npx

    - name: Build Docker image
      run: |
        docker buildx build --file Dockerfile --tag medusa:v1 .

    - name: Tag Docker image
      run: |
        docker tag medusa:v1 ${{vars.aws_account_id}}.dkr.ecr.${{vars.region}}.amazonaws.com/app-meducsa-repo:${{vars.GITHUB_JOB}}

    - name: Log in to ECR
      run: |
        aws ecr get-login-password --region ${{vars.region}} | docker login --username AWS --password-stdin ${{vars.aws_account_id}}.dkr.ecr.${{vars.region}}.amazonaws.com


    - name: Push Docker image
      run: |
        docker push ${{vars.aws_account_id}}.dkr.ecr.${{vars.region}}.amazonaws.com/app-meducsa-repo:${{vars.GITHUB_JOB}}
